matrix:
  fast_finish: true
  allow_failures:
  - php: 'master'
  include:
  - language: php
    php: '7.2'
  - language: php
    php: '7.3'
  - language: php
    php: '7.4'
  - language: php
    php: 'master'

addons:
  apt:
    packages:
    - lcov
    - libstemmer-dev

branches:
  only:
    - master
    - develop
    - travis

before_install:
  - source ./.ci/travis_php.sh
  - before_install
install: install
before_script: before_script
script: script
after_success: after_success
after_failure: after_failure
