name: linux

on:
  push:
    branches:
    - master
    - github-actions
    - ci
  pull_request:
    branches:
    - master

jobs:
  php72:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: I am tired of writing this shit in YAML and learning a new DSL for every CI service so I'm putting everything in a FSCKING BASH SCRIPT
      env:
        PHP_VERSION: "7.2"
      run: bash ./.github/workflows/linux.sh
  php73:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: I am tired of writing this shit in YAML and learning a new DSL for every CI service so I'm putting everything in a FSCKING BASH SCRIPT
      env:
        PHP_VERSION: "7.3"
      run: bash ./.github/workflows/linux.sh
  php74:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: I am tired of writing this shit in YAML and learning a new DSL for every CI service so I'm putting everything in a FSCKING BASH SCRIPT
      env:
        PHP_VERSION: "7.4"
      run: bash ./.github/workflows/linux.sh
